using LeetCode.Algorithms.DeleteNodeFromLinkedListPresentInArray;

namespace LeetCode.Tests.Algorithms.DeleteNodeFromLinkedListPresentInArray;

[TestClass]
public class DeleteNodeFromLinkedListPresentInArrayHashSetTests : DeleteNodeFromLinkedListPresentInArrayTestsBase<
    DeleteNodeFromLinkedListPresentInArrayHashSet>;