using LeetCode.Algorithms.ModifyGraphEdgeWeights;

namespace LeetCode.Tests.Algorithms.ModifyGraphEdgeWeights;

[TestClass]
public class ModifyGraphEdgeWeightsDijkstraTests : ModifyGraphEdgeWeightsTestsBase<ModifyGraphEdgeWeightsDijkstra>;