using LeetCode.Algorithms.MinimumNumberOfMovesToSeatEveryone;

namespace LeetCode.Tests.Algorithms.MinimumNumberOfMovesToSeatEveryone;

[TestClass]
public class MinimumNumberOfMovesToSeatEveryoneSortingTests : MinimumNumberOfMovesToSeatEveryoneTestsBase<
    MinimumNumberOfMovesToSeatEveryoneSorting>;