using LeetCode.Algorithms.MinimumIncrementToMakeArrayUnique;

namespace LeetCode.Tests.Algorithms.MinimumIncrementToMakeArrayUnique;

[TestClass]
public class MinimumIncrementToMakeArrayUniqueSortingTests : MinimumIncrementToMakeArrayUniqueTestsBase<
    MinimumIncrementToMakeArrayUniqueSorting>;