using LeetCode.Algorithms.FindModeInBinarySearchTree;

namespace LeetCode.Tests.Algorithms.FindModeInBinarySearchTree;

[TestClass]
public class FindModeInBinarySearchTreeDepthFirstSearchRecursiveTests : FindModeInBinarySearchTreeTestsBase<
    FindModeInBinarySearchTreeDepthFirstSearchRecursive>;