using LeetCode.Algorithms.FindModeInBinarySearchTree;

namespace LeetCode.Tests.Algorithms.FindModeInBinarySearchTree;

[TestClass]
public class FindModeInBinarySearchTreeDepthFirstSearchStackTests : FindModeInBinarySearchTreeTestsBase<
    FindModeInBinarySearchTreeDepthFirstSearchStack>;