using LeetCode.Algorithms.SplitLinkedListInParts;

namespace LeetCode.Tests.Algorithms.SplitLinkedListInParts;

[TestClass]
public class SplitLinkedListInPartsIterativeTests : SplitLinkedListInPartsTestsBase<SplitLinkedListInPartsIterative>;