using LeetCode.Algorithms.FindTheStudentThatWillReplaceTheChalk;

namespace LeetCode.Tests.Algorithms.FindTheStudentThatWillReplaceTheChalk;

[TestClass]
public class FindTheStudentThatWillReplaceTheChalkPrefixSumTests : FindTheStudentThatWillReplaceTheChalkTestsBase<
    FindTheStudentThatWillReplaceTheChalkPrefixSum>;