using LeetCode.Algorithms.IntersectionOfTwoArrays2;

namespace LeetCode.Tests.Algorithms.IntersectionOfTwoArrays2;

[TestClass]
public class IntersectionOfTwoArrays2SortingTests : IntersectionOfTwoArrays2TestsBase<IntersectionOfTwoArrays2Sorting>;