using LeetCode.Algorithms.MaximumProductOfTwoElementsInAnArray;

namespace LeetCode.Tests.Algorithms.MaximumProductOfTwoElementsInAnArray;

[TestClass]
public class MaximumProductOfTwoElementsInAnArraySecondBiggestTests : MaximumProductOfTwoElementsInAnArrayTestsBase<
    MaximumProductOfTwoElementsInAnArraySecondBiggest>;