<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\LeetCode\LeetCode.csproj" />
        <ProjectReference Include="..\LeetCode.Tests.Base\LeetCode.Tests.Base.csproj" />
    </ItemGroup>
</Project>