using LeetCode.Algorithms.MostStonesRemovedWithSameRowOrColumn;

namespace LeetCode.Tests.Algorithms.MostStonesRemovedWithSameRowOrColumn;

[TestClass]
public class MostStonesRemovedWithSameRowOrColumnUnionFindTests : MostStonesRemovedWithSameRowOrColumnTestsBase<
    MostStonesRemovedWithSameRowOrColumnUnionFind>;