// --------------------------------------------------------------------------------
// Copyright (C) 2026 Eugene Eremeev (also known as Yevhenii Yeriemeieiv).
// All Rights Reserved.
// --------------------------------------------------------------------------------
// This software is the confidential and proprietary information of Eugene Eremeev
// (also known as Yevhenii Yeriemeieiv) ("Confidential Information"). You shall not
// disclose such Confidential Information and shall use it only in accordance with
// the terms of the license agreement you entered into with Eugene Eremeev (also
// known as Yevhenii Yeriemeieiv).
// --------------------------------------------------------------------------------

namespace LeetCode.Algorithms.FindTheDifference;

/// <summary>
///     https://leetcode.com/problems/find-the-difference/
/// </summary>
public interface IFindTheDifference
{
    /// <summary>
    ///     Finds the letter that was added to <paramref name="t" />, which was generated by shuffling <paramref name="s" />
    ///     and adding one more letter at a random position.
    /// </summary>
    /// <param name="s">The original string.</param>
    /// <param name="t">The shuffled string with one extra letter.</param>
    /// <returns>The letter that was added to <paramref name="t" />.</returns>
    char FindTheDifference(string s, string t);
}