using LeetCode.Algorithms.SumOfDigitsOfStringAfterConvert;

namespace LeetCode.Tests.Algorithms.SumOfDigitsOfStringAfterConvert;

[TestClass]
public class SumOfDigitsOfStringAfterConvertIterativeTests :
    SumOfDigitsOfStringAfterConvertTestsBase<SumOfDigitsOfStringAfterConvertIterative>;