name: Coverage

on:
  pull_request:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test with Coverage
      run: dotnet test LeetCode.Tests/LeetCode.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./results/'

    - name: Check Coverage Threshold
      id: check-coverage
      run: |
        coverage=$(grep -Po 'Total\s+\|\s+\K\d+\.\d+(?=%)' ./results/coverage.info)
        threshold=90
        echo "Coverage: $coverage%"
        if (( $(echo "$coverage < $threshold" | bc -l) )); then
          echo "Coverage of $coverage% is below the required threshold of $threshold%"
          exit 1
        fi