name: .NET

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  pipeline:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ${{ github.workspace }}/global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests with Coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Check Code Style
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Generate Coverage Report
        run: |
          reportgenerator `
            -reports:"./Tests/**/TestResults/**/*.cobertura.xml" `
            -targetdir:coverage `
            -reporttypes:"HtmlInline_AzurePipelines;Cobertura;MarkdownSummaryGithub" `
            -historydir:coverage-history `
            -tag:${{ github.sha }}

      - name: Output Coverage Summary
        run: |
          $summary = Get-Content -Path "coverage/SummaryGithub.md" -Raw
          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY

      - name: Check Coverage Percentage
        if: github.event_name == 'pull_request'
        run: |
          $summary = Get-Content "coverage/SummaryGithub.md" -Raw
          if ($summary -match '\*\*Line coverage:\*\*\s+([\d.]+)%') {
              $coverage = [double]$matches[1]

              if ($coverage -lt 90) {
                  Write-Error "PR coverage below 90% ($coverage%)"
                  exit 1
              } else {
                  Write-Output "PR coverage OK ($coverage%)"
              }
          } else {
              Write-Error "Coverage value not found"
              exit 1
          }

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/source/coverage
          publish_branch: gh-pages
          keep_files: true
