name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build --no-restore
        working-directory: src
      - name: Run Tests with Coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
        working-directory: src
      - name: Generate Coverage Report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html
        working-directory: src
