name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  pipeline:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: source
    steps:
      - uses: actions/checkout@v3
      
      - name: Get .NET version from global.json
        id: dotnet-version
        run: |
          $dotnetVersion = (Get-Content -Raw -Path "../global.json" | ConvertFrom-Json).sdk.version
          echo "DOTNET_VERSION=$dotnetVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Run Tests with Coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
      - name: Install .NET Format tool
        run: dotnet tool install -g dotnet-format
      
      - name: Check Code Style
        run: dotnet format --verify-no-changes --verbosity diagnostic
      
      - name: Install Report Generator Tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      
      - name: Generate Coverage Report
        run: reportgenerator -reports:"./Tests/**/TestResults/**/coverage.cobertura.xml" -targetdir:coverage -reporttypes:"HtmlInline_AzurePipelines;Cobertura"
      
      - name: Generate Summary Report
        run: reportgenerator -reports:"./Tests/**/TestResults/**/coverage.cobertura.xml" -targetdir:coverage -reporttypes:"TextSummary"
      
      - name: Check Coverage Percentage
        run: |
          $coveragePercentage = (Get-Content -Path "coverage/Summary.txt" | Select-String -Pattern 'Line coverage:' | ForEach-Object { $_ -match '(\d+\.\d+)%' | Out-Null; $matches[1] })
          if ($coveragePercentage -lt 90) {
            Write-Error "Coverage is below 90%. It's at $coveragePercentage%"
            exit 1
          } else {
            Write-Output "Coverage is above 90%. It's at $coveragePercentage%"
      
      - name: Upload Coverage Report
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ github.workspace }}/source/coverage
      
      - name: Deploy to GitHub Pages
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./source/coverage
          publish_branch: gh-pages
          keep_files: true
