name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
      - name: Run Tests with Coverage
        run: |
          dotnet tool install --global coverlet.console
          coverlet --target "dotnet" --targetargs --no-build" --format opencover
      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console
      - name: Run Tests with Coverage for All Test Projects
        run: |
          find . -name '*.Tests.csproj' | while read testProject; do
            testDll="${testProject/.csproj/.dll}"
            testDllPath=${testDll/.\//./bin/Debug/net8.0/}
            echo "Running coverage for $testProject"
            coverlet "$testDllPath" --target "dotnet" --targetargs "test --no-build $testProject" --format opencover --merge-with coverage.json -o coverage.json
          done
      - name: Check Coverage Percentage
        run: |
          coveragePercentage=$(grep 'Linecoverage' coverage.json | sed -n 's/.*Linecoverage=\"\([0-9.]*\)%\".*/\1/p')
          echo "Code Coverage: $coveragePercentage%"
          if (( $(echo "$coveragePercentage < 90" | bc -l) )); then
            echo "Coverage is below 90%. It's at $coveragePercentage%"
            exit 1
          fi
