name: .NET

on:
  push:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test with Coverage
      run: dotnet test LeetCode.Tests/LeetCode.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./results/'

    - name: Install ReportGenerator Tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Add ReportGenerator to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Generate Coverage Report
      run: reportgenerator "-reports:./LeetCode.Tests/results/coverage.info" "-targetdir:./LeetCode.Tests/results" "-reporttypes:Html"
      
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: LeetCode.Tests/results